-- MySQL Script generated by MySQL Workbench
-- Sat Sep 21 12:20:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema senac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salas` (
  `id_sala` INT NOT NULL,
  `tipo_sala` VARCHAR(45) NULL,
  `andar` INT NULL,
  `capacidade` INT NULL COMMENT 'capacidade das salas (lotação)',
  `maquinas_qtd` INT NULL,
  `maquinas_tipo` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disciplinas` (
  `id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL,
  `curso` VARCHAR(80) NULL,
  `docente` VARCHAR(50) NULL,
  `turno` VARCHAR(10) NULL,
  `turma` VARCHAR(2) NULL,
  `codigo` VARCHAR(60) NULL,
  `participantes_qtd` INT NULL,
  PRIMARY KEY (`id_disciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservas` (
  `id_reservas` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `tipo_reserva` VARCHAR(30) NULL,
  `id_sala` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_reservas`),
    FOREIGN KEY (`id_sala`)
    REFERENCES `salas` (`id_sala`),
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `disciplinas` (`id_disciplina`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


--
-- Dumping data for table `salas`
--

INSERT INTO `salas` (`id_sala`, `tipo_sala`, `capacidade`, `maquinas_qtd`, `maquinas_tipo`, `descricao`) VALUES
(101,'Laboratório',20, 20,'intel-i5-7',NULL),
(102,'Laboratório',40, 30,'intel-i5-7',NULL),
(103,'Laboratório',30, 20,'intel-i3-7',NULL),
(104,'Auditório',100,2,'Intel-i3-7',NULL),
(105,'Laboratório',30,20,'Intel-i3-7',NULL),
(122,'Estudio de Aúdio',10,2,'Intel-i3-7',NULL),
(201,'Laboratório',30,30,'Rizen-5',NULL),
(202,'Laboratório',40,30,'Rizen-5',NULL),
(203,'Laboratório',35,20,'Rizen-5',NULL),
(204,'Laboratório',45,30,'Rizen-5',NULL),
(205,'Laboratório',45,30,'Rizen-5',NULL),
(301,'Laboratório',25,20,'Intel-i9-12', NULL),
(302,'Laboratório',25,20,'Intel-i9-12', NULL),
(303,'Laboratório',25,20,'Intel-i9-12', NULL),
(304,'Laboratório',45,35,'MAC',NULL),
(305,'Laboratório',45,35,'MAC',NULL),
(306,'Laboratório',45,35,'MAC',NULL),
(307,'Laboratório',30,30,'Intel-i7-10', NULL),
(401,'Sala de aula',40,0,NULL,NULL),
(402,'Sala de aula',50,0,NULL,NULL),
(403,'Sala de aula',40,0,NULL,NULL),
(404,'Sala de aula',60,0,NULL,NULL),
(501,'Laboratório',30,30,'Rizen-5',NULL),
(502,'Laboratório',50,30,'Rizen-5',NULL),
(503,'Laboratório',25,25,'Rizen-5',NULL),
(504,'Laboratório',50,35,'Rizen-5',NULL),
(505,'Laboratório',50,35,'Rizen-5',NULL),
(601,'Laboratório',30,30,'Intel-i5-6',NULL),
(602,'Laboratório',40,28,'Intel-i5-6',NULL),
(603,'Laboratório',20,22,'Intel-i5-6',NULL),
(604,'Laboratório',30,35,'Intel-i5-6',NULL),
(605,'Laboratório',30,30,'Intel-i5-6',NULL),
(801,'Auditório',100,1,'Intel-i7-10',NULL),
(802,'Auditório',80, 1,'Intel-i7-10',NULL),
(803,'Auditório',150,1,'Intel-i7-10',NULL);


--
-- Dumping data for table `disciplinas`
--

INSERT INTO `disciplinas` (`id_disciplina`, `nome`,`curso`, `docente`, `turno`, `codigo`,`participantes_qtd`) VALUES
(1, 'Desenvolvimento Interface Web','SPI', 'Fernando', 'Manhã', 'RS-20231-FSPOA-DlW-PRE-SPI1M24-1A',20),
(2, 'Desenvolvimento Interface Web','SPI', 'Fernando', 'Noite', 'RS-20231-FSPOA-DlW-PRE-SPI1N24-1A',25),
(3, 'Desenvolvimento Interface Web','SPI', 'Rafael', 'Manhã', 'RS-20231-FSPOA-DlW-PRE-SPI1M24-1A',24),
(4, 'Desenvolvimento Interface Web','SPI', 'Rafael', 'Noite', 'RS-20231-FSPOA-DlW-PRE-SPI1N24-1A',22),
(5, 'Desenvolvimento Gráfico','PM', 'Roberto', 'Manhã', 'RS-20242-FSPOA-DGR-PRE-PM1M24-2',18),
(6, 'Desenvolvimento Gráfico','PM', 'Roberto', 'Noite', 'RS-20242-FSPOA-DGR-PRE-PM1N24-2',25),
(7, 'Desenvolvimento Gráfico','PM', 'Pedro', 'Manhã', 'RS-20242-FSPOA-DGR-PRE-PM1M24-2',28),
(8, 'Desenvolvimento Gráfico','PM', 'Pedro', 'Noite', 'RS-20242-FSPOA-DGR-PRE-PM1N24-2',12),
(9, 'Algoritmos Estruturas de Dados I', 'ADS', 'Roberto', 'Manhã', 'RS-20232-FSPOA-ALG1-PRE-ADS3M24-2',27),
(10, 'Algoritmos Estruturas de Dados I','ADS', 'Roberto', 'Noite', 'RS-20232-FSPOA-ALG1-PRE-ADS3N24-2',22),
(11, 'Algoritmos Estruturas de Dados I','ADS', 'Mario', 'Manhã', 'RS-20232-FSPOA-ALG1-PRE-ADS3M24-2',31),
(12, 'Algoritmos Estruturas de Dados I','ADS', 'Mario', 'Noite', 'RS-20232-FSPOA-ALG1-PRE-ADS3N24-2',20),
(13, 'Fundamentos Computacionais','ADS', 'Reinaldo', 'Manhã', 'RS-20222-FSPOA-FUND-PRE-ADS1M24-2',19),
(14, 'Fundamentos Computacionais','ADS', 'Reinaldo', 'Noite', 'RS-20222-FSPOA-FUND-PRE-ADS1N24-2',24),
(15, 'Fundamentos Computacionais','ADS', 'Ronaldo', 'Manhã', 'RS-20222-FSPOA-FUND-PRE-ADS1M24-2',22),
(16, 'Fundamentos Computacionais','ADS', 'Ronaldo', 'Noite', 'RS-20222-FSPOA-FUND-PRE-ADS1N24-2',26);

--
-- Dumping data for table `reservas`
-- 

INSERT INTO `reservas`( `data`, `tipo_reserva`, `id_sala`, `id_disciplina`) VALUES 

-- diciplina (9, 'Algoritmos Estruturas de Dados I', 'Roberto', 'Manhã', '2024-M-1-A')

('2024-03-04','Semanal',504,9),
('2024-03-11','Semanal',504,9),
('2024-03-18','Semanal',504,9),
('2024-03-25','Semanal',504,9),
('2024-04-01','Semanal',504,9),
('2024-04-08','Semanal',504,9),
('2024-04-15','Semanal',504,9),
('2024-04-22','Semanal',504,9),
('2024-04-29','Semanal',504,9),
('2024-05-06','Semanal',504,9),
('2024-05-13','Semanal',504,9),
('2024-05-20','Semanal',504,9),
('2024-05-27','Semanal',504,9),
('2024-06-03','Semanal',504,9),
('2024-06-10','Semanal',504,9),
('2024-06-17','Semanal',504,9),
('2024-06-24','Semanal',504,9),
('2024-07-01','Semanal',504,9),
('2024-07-08','Semanal',504,9),
('2024-07-15','Semanal',504,9),
('2024-07-22','Semanal',504,9),

-- diciplina (10, 'Algoritmos Estruturas de Dados I', 'Roberto', 'Noite', '2024-N-2-A')

('2024-03-04','Semanal',504,10),
('2024-03-11','Semanal',504,10),
('2024-03-18','Semanal',504,10),
('2024-03-25','Semanal',504,10),
('2024-04-01','Semanal',504,10),
('2024-04-08','Semanal',504,10),
('2024-04-15','Semanal',504,10),
('2024-04-22','Semanal',504,10),
('2024-04-29','Semanal',504,10),
('2024-05-06','Semanal',504,10),
('2024-05-13','Semanal',504,10),
('2024-05-20','Semanal',504,10),
('2024-05-27','Semanal',504,10),
('2024-06-03','Semanal',504,10),
('2024-06-10','Semanal',504,10),
('2024-06-17','Semanal',504,10),
('2024-06-24','Semanal',504,10),
('2024-07-01','Semanal',504,10),
('2024-07-08','Semanal',504,10),
('2024-07-15','Semanal',504,10),
('2024-07-22','Semanal',504,10),

-- diciplina (5, 'Desenvolvimento Gráfico', 'Roberto', 'Manhã', '2024-M-2-A')

('2024-03-04','Semanal',303,5),
('2024-03-11','Semanal',303,5),
('2024-03-18','Semanal',303,5),
('2024-03-25','Semanal',303,5),
('2024-04-01','Semanal',303,5),
('2024-04-08','Semanal',303,5),
('2024-04-15','Semanal',303,5),
('2024-04-22','Semanal',303,5),
('2024-04-29','Semanal',303,5),
('2024-05-06','Semanal',303,5),
('2024-05-13','Semanal',303,5),
('2024-05-20','Semanal',303,5),
('2024-05-27','Semanal',303,5),
('2024-06-03','Semanal',303,5),
('2024-06-10','Semanal',303,5),
('2024-06-17','Semanal',303,5),
('2024-06-24','Semanal',303,5),
('2024-07-01','Semanal',303,5),
('2024-07-08','Semanal',303,5),
('2024-07-15','Semanal',303,5),
('2024-07-22','Semanal',303,5),

-- diciplina (6, 'Desenvolvimento Gráfico', 'Roberto', 'Noite', '2024-N-1-A')

('2024-03-04','Semanal',301,6),
('2024-03-11','Semanal',301,6),
('2024-03-18','Semanal',301,6),
('2024-03-25','Semanal',301,6),
('2024-04-01','Semanal',301,6),
('2024-04-08','Semanal',301,6),
('2024-04-15','Semanal',301,6),
('2024-04-22','Semanal',301,6),
('2024-04-29','Semanal',301,6),
('2024-05-06','Semanal',301,6),
('2024-05-13','Semanal',301,6),
('2024-05-20','Semanal',301,6),
('2024-05-27','Semanal',301,6),
('2024-06-03','Semanal',301,6),
('2024-06-10','Semanal',301,6),
('2024-06-17','Semanal',301,6),
('2024-06-24','Semanal',301,6),
('2024-07-01','Semanal',301,6),
('2024-07-08','Semanal',301,6),
('2024-07-15','Semanal',301,6),
('2024-07-22','Semanal',301,6),

-- (1, 'Desenvolvimento Interface Web', 'Fernando', 'Manhã', '2024-M-1-A')

('2024-03-05','Semanal',502,1),
('2024-03-12','Semanal',502,1),
('2024-03-19','Semanal',502,1),
('2024-03-26','Semanal',502,1),
('2024-04-02','Semanal',502,1),
('2024-04-09','Semanal',502,1),
('2024-04-16','Semanal',502,1),
('2024-04-23','Semanal',502,1),
('2024-04-30','Semanal',502,1),
('2024-05-07','Semanal',502,1),
('2024-05-14','Semanal',502,1),
('2024-05-21','Semanal',502,1),
('2024-05-28','Semanal',502,1),
('2024-06-04','Semanal',502,1),
('2024-06-11','Semanal',502,1),
('2024-06-18','Semanal',502,1),
('2024-06-25','Semanal',502,1),
('2024-07-02','Semanal',502,1),
('2024-07-09','Semanal',502,1),
('2024-07-16','Semanal',502,1),
('2024-07-23','Semanal',502,1),

-- (1, 'Desenvolvimento Interface Web', 'Fernando', 'Manhã', '2024-M-1-A')

('2024-03-06','Semanal',602,1),
('2024-03-13','Semanal',602,1),
('2024-03-14','Semanal',602,1),
('2024-03-27','Semanal',602,1),
('2024-04-03','Semanal',602,1),
('2024-04-10','Semanal',602,1),
('2024-04-17','Semanal',602,1),
('2024-04-24','Semanal',602,1),
('2024-05-01','Semanal',602,1),
('2024-05-08','Semanal',602,1),
('2024-05-15','Semanal',602,1),
('2024-05-22','Semanal',602,1),
('2024-05-29','Semanal',602,1),
('2024-06-05','Semanal',602,1),
('2024-06-12','Semanal',602,1),
('2024-06-19','Semanal',602,1),
('2024-06-26','Semanal',602,1),
('2024-07-03','Semanal',602,1),
('2024-07-10','Semanal',602,1),
('2024-07-17','Semanal',602,1),
('2024-07-24','Semanal',602,1);